services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semoule
      MYSQL_USER: zizoujab
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/semoule
    depends_on:
      - database
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ../app:/var/www/semoule
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  ocr:
    build:
      context: ./ocr  # Path to your OCR Docker setup
    volumes:
      - ../ocr/ocr_images:/app/ocr_images  # Folder where OCR will access the image files
      - ../ocr/src:/app/src  # Folder where OCR will execute some python scripts
    ports:
      - '8000:5000'
    environment:
      - FLASK_ENV=development  # Enable Flask development mode