services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semoule
      MYSQL_USER: zizoujab
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../backend:/var/www/semoule
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ../backend:/var/www/semoule
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  ocr:
    build:
      context: ocr
    volumes:
      - ../ocr:/app
    ports:
      - "8000:5000"
  svelte:
    image: node:18-alpine  # Use Node.js to build and serve Svelte app
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - '80:5173'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - php